/**
 * Categorization pass: reads scripts/data/raw_videos.json and writes src/data/videos.json
 * Run: node scripts/categorize.mjs
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const raw = JSON.parse(readFileSync(join(__dirname, 'data/raw_videos.json'), 'utf8'));

// Categorization keyed by video ID.
// Fields: project, videoType, instruments, tags
// project:   "Wintergatan Band" | "Marble Machine" | "Marble Machine X" |
//            "Marble Machine 3" | "Music Box" | "Cyber Bass" | "Speelklok" | "Other"
// videoType: "music" | "build-log" | "prototype-test" | "workshop-tour" |
//            "channel-update" | "educational" | "inspiration" | "philosophical" |
//            "live-stream"
// instruments: specific instruments/components being discussed or tested
//   Musical: accordion banjo bass cyber-bass drums guitar hackbrett harp hi-hat kick-drum
//            melodica musical-saw ondophone percussion sizzle-cymbal snare-drum strings
//            tambourine vibraphone violin
//   Machine components: bearings bowden-cable clock clutch collapsable-wheel conveyor-belt
//            counterweight damper drivetrain escapement flyball-governor flywheel frame gears
//            lego magnets marble-demagnetizer marble-divider marble-funnel marble-gates
//            marble-lift marble-loop marble-release marble-tracks motor muting-system
//            paper-pull-mechanism pedal programming-wheel resonator rhythm-machine
//            timing trigger-mechanism vibrato
//   Engineering: machining wiring
//   Other: other
// tags: freeform search keywords

const CAT = {
  // ── Wintergatan Band music videos (2013–2014) ───────────────────────────
  "SBK2AF-NdVA": { project:"Wintergatan Band", videoType:"music", instruments:["accordion","drums"], tags:["sommarfågel","band"] },
  "rEeiRXOlWUE": { project:"Wintergatan Band", videoType:"music", instruments:["other"], tags:["starmachine2000","band"] },
  "O0_r0SKc2oc": { project:"Wintergatan Band", videoType:"music", instruments:["accordion","drums"], tags:["sommarfågel","album","band"] },
  "2you195xEQI": { project:"Wintergatan Band", videoType:"music", instruments:["accordion","strings"], tags:["valentine","album","band"] },
  "3yCaMM8can0": { project:"Wintergatan Band", videoType:"music", instruments:["vibraphone","guitar","drums"], tags:["västanberg","album","band"] },
  "CJzcrpP1agQ": { project:"Wintergatan Band", videoType:"music", instruments:["accordion","drums"], tags:["tornado","album","band"] },
  "Mh0fhdfZcfM": { project:"Wintergatan Band", videoType:"music", instruments:["accordion"], tags:["slottskogen","disc golf","album","band"] },
  "Mx3z2_58Ozc": { project:"Wintergatan Band", videoType:"music", instruments:["accordion","vibraphone","drums"], tags:["paradis","album","band"] },
  "jRC49qUCp9Y": { project:"Wintergatan Band", videoType:"music", instruments:["accordion"], tags:["all was well","album","band"] },
  "p1rBhosS7LM": { project:"Wintergatan Band", videoType:"music", instruments:["accordion","drums"], tags:["the rocket","album","band"] },
  "t35T341NACk": { project:"Wintergatan Band", videoType:"music", instruments:["accordion"], tags:["biking is better","album","band"] },
  "xBoLYV1x8Ew": { project:"Wintergatan Band", videoType:"music", instruments:["other"], tags:["starmachine2000","album","band"] },
  "1eb0Q5vkafc": { project:"Wintergatan Band", videoType:"music", instruments:["other"], tags:["starmachine2000","fan cover","stop motion"] },
  "90UFsmesu4Y": { project:"Wintergatan Band", videoType:"music", instruments:["accordion","vibraphone"], tags:["visa från utanmyra","folk"] },

  // ── Speelklok museum visit 2014 ──────────────────────────────────────────
  "FkJgug5ycZE": { project:"Speelklok", videoType:"inspiration", instruments:["other"], tags:["museum","self-playing","speelklok"] },

  // ── Original Marble Machine – Prologue build series (2014–2016) ─────────
  "luXd-DNgd48": { project:"Marble Machine", videoType:"build-log", instruments:[], tags:["marble machine","prologue","planning"] },
  "akFt5zSWw8Y": { project:"Marble Machine", videoType:"build-log", instruments:[], tags:["marble machine","prologue","planning"] },
  "LqN1N3JP63Q": { project:"Wintergatan Band", videoType:"behind-the-scenes", instruments:["accordion","vibraphone"], tags:["visa från utanmyra","making of"] },
  "tMW0-xcuhhs": { project:"Marble Machine", videoType:"prototype-test", instruments:["sizzle cymbal"], tags:["marble machine","prologue","cymbal","sound test"] },
  "bwTdGVNWB1M": { project:"Marble Machine", videoType:"prototype-test", instruments:["vibraphone","marble funnel"], tags:["marble machine","prologue","vibraphone","funnel"] },
  "1GbMYvYZEHc": { project:"Marble Machine", videoType:"prototype-test", instruments:["marble lift"], tags:["marble machine","prologue","lift","mechanism"] },
  "ebRh-Q-GCVQ": { project:"Marble Machine", videoType:"build-log", instruments:["gears"], tags:["marble machine","prologue","gears","mechanism"] },
  "B_FX18uoFIA": { project:"Marble Machine", videoType:"prototype-test", instruments:["flywheel"], tags:["marble machine","prologue","flywheel"] },
  "S27Inwu-w6Q": { project:"Marble Machine", videoType:"prototype-test", instruments:["kick drum"], tags:["marble machine","kick drum","sound test"] },
  "NQ0nj6wrjyA": { project:"Marble Machine", videoType:"build-log", instruments:[], tags:["marble machine","finished","2000 marbles","3000 parts"] },
  "IvUU8joBb1Q": { project:"Marble Machine", videoType:"music", instruments:["vibraphone","bass","sizzle cymbal"], tags:["marble machine","viral","2000 marbles"] },
  "uog48viZUbM": { project:"Marble Machine", videoType:"educational", instruments:["vibraphone","bass","sizzle cymbal","programming wheel"], tags:["marble machine","how it works","part 1"] },
  "p0Guq7vZb_E": { project:"Marble Machine", videoType:"educational", instruments:["vibraphone","bass","sizzle cymbal","marble lift"], tags:["marble machine","how it works","part 2"] },

  // ── Music Box builds & Modulin (mid-2016) ────────────────────────────────
  "mFfe4ZRQOH8": { project:"Music Box", videoType:"music", instruments:["other"], tags:["music box","modulin","all was well","two instruments"] },
  "Lf5Qw1kTbzY": { project:"Music Box", videoType:"prototype-test", instruments:["paper pull mechanism"], tags:["music box","build","mechanism"] },
  "1o05wMe4am0": { project:"Music Box", videoType:"prototype-test", instruments:["collapsable wheel"], tags:["music box","build","wheel"] },
  "44HKxVY2Z_I": { project:"Other", videoType:"behind-the-scenes", instruments:[], tags:["diresta","collaboration","workshop"] },

  // ── Live concerts and band content (2016) ───────────────────────────────
  "F22DCvJ24Eg": { project:"Marble Machine", videoType:"music", instruments:["vibraphone","bass","sizzle cymbal"], tags:["marble machine","live","band version"] },
  "mf3bhAayHaw": { project:"Wintergatan Band", videoType:"music", instruments:["accordion"], tags:["starmachine2000","live","haldern pop"] },
  "FHjdI7l3WDc": { project:"Wintergatan Band", videoType:"music", instruments:["accordion"], tags:["tornado","valentine","live","steadicam"] },
  "NPOz7bTc7W0": { project:"Marble Machine", videoType:"channel-update", instruments:[], tags:["marble machine","piano version","announcement"] },
  "6qkFVWJWRUI": { project:"Marble Machine", videoType:"music", instruments:["other"], tags:["marble machine","piano cover"] },
  "0rdEhaZN54Y": { project:"Marble Machine", videoType:"educational", instruments:[], tags:["marble machine","piano tutorial"] },

  // ── 2017 plans, MMX kickoff ──────────────────────────────────────────────
  "Ld7zTApixXE": { project:"Other", videoType:"channel-update", instruments:[], tags:["2017 plans","marble machine x","double album","channel update"] },
  "61QtAEfEEeg": { project:"Wintergatan Band", videoType:"music", instruments:["accordion"], tags:["sommarfågel","live","haldern pop","behind the scenes"] },

  // ── Marble Machine X build series ───────────────────────────────────────
  "g8X0nJHrJ9g": { project:"Marble Machine X", videoType:"prototype-test", instruments:["kick drum"], tags:["kick drum","90 degree","fail","prototype"] },
  "C8qyVURtSZc": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #1","first sketches","design"] },
  "dcosgma0l-Q": { project:"Marble Machine X", videoType:"prototype-test", instruments:["kick drum"], tags:["kick drum","90 degree","solution","viewers"] },
  "OXD8hdsxsTA": { project:"Marble Machine X", videoType:"prototype-test", instruments:[], tags:["mmx #2","prototyping","early stage"] },

  // ── Music Box & Modulin content (early 2017) ────────────────────────────
  "UrhL_jBi2aA": { project:"Music Box", videoType:"music", instruments:["melodica"], tags:["all was well","music box","melodica"] },
  "QaW5K85UDR0": { project:"Other", videoType:"music", instruments:["other"], tags:["modulin","mega man","dr wily","video game music"] },
  "MUdWeBYe3GY": { project:"Other", videoType:"educational", instruments:[], tags:["modulin","how it works","DIY","theremin"] },

  // ── More MMX build ───────────────────────────────────────────────────────
  "tGrm-KMPsXE": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #3","revisiting first machine"] },
  "OacXT6Nk0LE": { project:"Music Box", videoType:"build-log", instruments:[], tags:["music box","build from scratch","full build"] },
  "M8R8iFf9ltE": { project:"Marble Machine", videoType:"channel-update", instruments:[], tags:["marble machine","covers","reaction","community"] },
  "5dyUKDWKxxY": { project:"Wintergatan Band", videoType:"music", instruments:["accordion"], tags:["paradis","live"] },
  "GMuuLEF0a84": { project:"Wintergatan Band", videoType:"music", instruments:["accordion","guitar","drums","vibraphone"], tags:["full concert","victoriateatern","live"] },
  "UHXm1kqQOw4": { project:"Marble Machine X", videoType:"prototype-test", instruments:["bass"], tags:["mmx #4","bass","marbles","string striking"] },
  "Ypb9eWOpiPg": { project:"Marble Machine X", videoType:"prototype-test", instruments:["drums"], tags:["mmx #5","3D printed drums","prototype"] },
  "_CeL5o_fyTQ": { project:"Other", videoType:"music", instruments:["other"], tags:["piano","boat","spontaneous"] },
  "PoYmoCUvGqM": { project:"Marble Machine", videoType:"build-log", instruments:[], tags:["marble machine","disassembly","speelklok"] },
  "XbQjtEoK0Cs": { project:"Marble Machine X", videoType:"prototype-test", instruments:["drums"], tags:["mmx #6","3D printed drums","test"] },
  "HjBhO9iqEc0": { project:"Music Box", videoType:"educational", instruments:[], tags:["music box","programming","hole punch","tutorial"] },
  "XyVyA5ZdWOY": { project:"Music Box", videoType:"music", instruments:["other"], tags:["music box","positivity"] },
  "qkAwf3hlHSE": { project:"Marble Machine", videoType:"behind-the-scenes", instruments:[], tags:["marble machine","speelklok","museum","retired"] },
  "sY-lnq-4X5Y": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #7","3 days provence","workshop"] },
  "uoHdcA_xass": { project:"Other", videoType:"channel-update", instruments:[], tags:["500k subscribers","Q&A","livestream"] },
  "X9HNJrXk5fY": { project:"Other", videoType:"channel-update", instruments:[], tags:["break","channel update"] },
  "CNqktpl5syk": { project:"Other", videoType:"channel-update", instruments:[], tags:["welcome back","wintergatan wednesdays"] },

  // ── Speelklok / Music Machine Mondays (2017) ────────────────────────────
  "xs0mP2cOmJs": { project:"Speelklok", videoType:"inspiration", instruments:["violin"], tags:["self-playing violin","phonolizt","museum","automata"] },
  "FNZ3stsXlYI": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #8","CNC","workshop"] },
  "OsjG1aEdogw": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["carillon","500 year old","improvisation"] },
  "2H50Ur7_Qqw": { project:"Marble Machine X", videoType:"behind-the-scenes", instruments:[], tags:["mmx","first vs second machine","comparison"] },
  "LyXY4Bz3PLs": { project:"Speelklok", videoType:"inspiration", instruments:["other"], tags:["polyphon","disc changing","music box","museum"] },
  "8k3Ga8YaH4U": { project:"Marble Machine X", videoType:"workshop-tour", instruments:[], tags:["mmx #10","new workshop","move"] },
  "PdOnJwGxGH0": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["fairground organ","marble machine song","museum"] },
  "5UpriHcn_xs": { project:"Speelklok", videoType:"inspiration", instruments:["violin","percussion"], tags:["self-playing","philipps paganini","17 instruments","museum"] },
  "QQkORTTKK4k": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #11","steel frame","welding","metal"] },
  "ADDcetK6-nY": { project:"Speelklok", videoType:"inspiration", instruments:["other"], tags:["automata organ","200 year old","magic trick","museum"] },
  "smBwg6MAvLQ": { project:"Marble Machine X", videoType:"build-log", instruments:["gears"], tags:["mmx #12","plywood gears"] },
  "ZSJ7UH-gksY": { project:"Speelklok", videoType:"inspiration", instruments:["other"], tags:["self-playing piano","pedal powered","1925","karaoke","museum"] },
  "xZSmyg-1fFU": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble lift","magnets"], tags:["mmx #13","lifting marbles","magnets"] },
  "6CQgzqYuo04": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["domtoren","clock tower","marble machine song","museum"] },
  "twmcxtz2PD4": { project:"Marble Machine X", videoType:"build-log", instruments:["programming wheel"], tags:["mmx #14","programming wheel","skeleton"] },
  "9uMRD2o6dJo": { project:"Speelklok", videoType:"inspiration", instruments:["other"], tags:["steinway","duo-art","pianola","prokofiev","museum"] },
  "x8sUtK2QRfs": { project:"Marble Machine X", videoType:"build-log", instruments:["marble tracks"], tags:["mmx #15","marble tracks"] },
  "VAHODmqkCi4": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["street organ","first time playing","museum"] },
  "PlvqudZ4z2k": { project:"Speelklok", videoType:"behind-the-scenes", instruments:[], tags:["speelklok","workshop","museum tour"] },
  "7hYX67CZd28": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #16","158 plywood parts"] },
  "sV8NE_JYxKU": { project:"Speelklok", videoType:"inspiration", instruments:["clock"], tags:["musical clock","1750","porter music box","museum"] },
  "pyWCEIbqPBs": { project:"Marble Machine X", videoType:"prototype-test", instruments:["trigger mechanism"], tags:["mmx #17","trigger mechanism"] },
  "_VlnSOQxcac": { project:"Speelklok", videoType:"inspiration", instruments:["other"], tags:["gavioli","dance organ","fairground","museum"] },
  "7J6eSGYBwPk": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #18","moved to france"] },
  "zjMImqFn3AI": { project:"Marble Machine X", videoType:"build-log", instruments:["programming wheel"], tags:["mmx #19","programming wheel skeleton"] },
  "-Rz9JcOaZw4": { project:"Speelklok", videoType:"inspiration", instruments:["other"], tags:["haydn","220 year old","mechanical organ","earliest recording","museum"] },
  "HO7VMJ2fVBo": { project:"Marble Machine", videoType:"behind-the-scenes", instruments:[], tags:["marble machine","speelklok","building at museum"] },
  "wIiDQ7buWLs": { project:"Other", videoType:"channel-update", instruments:[], tags:["music machine mondays","finale","channel update"] },
  "d5t3bbsJpYk": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["music machine mondays","theme song"] },
  "X5TmNHoV1F0": { project:"Speelklok", videoType:"inspiration", instruments:["other"], tags:["speelklok","top 10","museum","self-playing instruments"] },
  "xR6vZtnoMlQ": { project:"Marble Machine", videoType:"behind-the-scenes", instruments:[], tags:["marble machine","speelklok","meet and greet","tour"] },

  // ── Speelklok individual clips (Dec 15, 2017) ───────────────────────────
  "qgEOZSzSDwA": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["tivoli organ","museum","speelklok"] },
  "4V6KBcEJjro": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["cylinder music box","museum","speelklok"] },
  "VNdfm_XBjl0": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["carillon","magic flute","museum","speelklok"] },
  "A9Xsi_0ZMPE": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["haydn niemecz","mechanical organ","museum","speelklok"] },
  "RXp3y_WoKck": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["aalster gaviola","fairground organ","museum","speelklok"] },
  "NTC3Kq1oFEA": { project:"Speelklok", videoType:"music", instruments:["clock"], tags:["allin walker","table clock","museum","speelklok"] },
  "TGwKTaDVAfg": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["porter music box","radetzkymars","museum","speelklok"] },
  "IqPWDinx03A": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["snuff box","music box","museum","speelklok"] },
  "YZeacPXrLgQ": { project:"Speelklok", videoType:"music", instruments:["harp"], tags:["pianoharp","swedish table","museum","speelklok"] },
  "v2o85G-CWFw": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["kalliope","panorama","music box","museum","speelklok"] },
  "Dkh5zmPz4ZU": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["drie pruiken","street organ","adiós nonino","museum","speelklok"] },
  "QZ_gyfDXMk8": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["steinway","duo-art","pianola","museum","speelklok"] },
  "a05-r0VcCZQ": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["domtoren","clock tower","marble machine song","museum","speelklok"] },
  "ama6XBVDbZM": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["grandiola","player piano","museum","speelklok"] },
  "_s4-VeuXUdk": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["perlee","demonstration organ","museum","speelklok"] },
  "TC6YgCLvt5g": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["bruder barrel","automata organ","museum","speelklok"] },
  "S6CiJfJS0s4": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["philipps pianella","paganini","museum","speelklok"] },
  "jUApoagh64U": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["de schuyt","street organ","marble machine song","museum","speelklok"] },
  "blkdd-pPEcA": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["polyphon","disc changing","washington post","museum","speelklok"] },
  "t8-CKUC1dWQ": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["carillon","improvisation","museum","speelklok"] },
  "o3SecHzbN2E": { project:"Speelklok", videoType:"music", instruments:["violin"], tags:["phonolizt violina","self-playing violin","pasadena","museum","speelklok"] },

  // ── MMX build continues (2018) ───────────────────────────────────────────
  "ThYMEYtYC8o": { project:"Music Box", videoType:"music", instruments:["harp","hackbrett"], tags:["wintergatan soundtrack","music box","harp","hackbrett"] },
  "X_Ch70KkMtE": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble divider"], tags:["mmx #21","marble divider"] },
  "F0nwRnL2hPU": { project:"Music Box", videoType:"music", instruments:["other"], tags:["wintergatan soundtrack","moon and star","music box"] },
  "2rAl4Hd7CHA": { project:"Marble Machine X", videoType:"workshop-tour", instruments:[], tags:["mmx #22","dream workshop","build"] },
  "V8OUVHlpnag": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble demagnetizer"], tags:["mmx #23","marble demagnetizer","mechanical"] },
  "SkI22V_v-xY": { project:"Marble Machine X", videoType:"build-log", instruments:["gears"], tags:["mmx #24","plywood gears","precision"] },
  "iFuUSe44jtk": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates","magnets"], tags:["mmx #25","magnet midi","music system","magnets"] },
  "2xgWuw3TOJA": { project:"Other", videoType:"channel-update", instruments:["musical saw"], tags:["musical saw","sponsorships","channel update"] },
  "vtOt2j-U3tM": { project:"Marble Machine X", videoType:"build-log", instruments:["rhythm machine"], tags:["mmx #26","rhythm machine","new features"] },
  "zA2YazzURlg": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #27","darth marius","build team"] },
  "4ELi8IWrLKI": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #20","lazy susan","turntable"] },
  "NOBdfmAcvwQ": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble divider"], tags:["mmx #28","divide by 8","marble divider"] },
  "g5c2Htj8Vtw": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble lift"], tags:["mmx #29","fish stair","marble lift","evolution"] },
  "JKjb1oQIBcs": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #30","spring tension beam","CAD"] },
  "6zi9NvaXfOM": { project:"Other", videoType:"channel-update", instruments:[], tags:["olive oil","community","fun"] },
  "9zL8pRDxPck": { project:"Marble Machine X", videoType:"educational", instruments:[], tags:["mmx #31","fusion 360","large assemblies","CAD"] },
  "A-_Lkq0O9is": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble lift"], tags:["mmx #32","ratchet","marble lift"] },
  "5ZBb0jidgwQ": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble lift","conveyor belt"], tags:["mmx #33","conveyor belt","marble lift"] },
  "Ur0b6hh9joM": { project:"Other", videoType:"educational", instruments:[], tags:["fusion 360","tutorial","large assemblies","CAD"] },
  "z0_EliD9G90": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble lift"], tags:["mmx #34","3D printed","marble lift"] },
  "aleY_84rOiY": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #35","3D printer","calibration"] },
  "8gUQA7jUNoo": { project:"Marble Machine X", videoType:"build-log", instruments:["gears"], tags:["mmx #36","planetary gears"] },
  "_roikOlK-OI": { project:"Marble Machine X", videoType:"build-log", instruments:["marble gates"], tags:["mmx #37","CNC plasma cut","magnet levers"] },
  "Xcf4ABsMEQI": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #38","TIG welding","first time"] },
  "R50B5XaWUPM": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble demagnetizer"], tags:["mmx #39","marble demagnetizer","v2"] },
  "t3kIptC3Zhg": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble divider"], tags:["mmx #40","marble divider","fail"] },
  "TQ0yPYk_luw": { project:"Marble Machine X", videoType:"build-log", instruments:["muting system","vibraphone"], tags:["mmx #41","muting system","assembly"] },
  "F8EJlgAsdy8": { project:"Marble Machine X", videoType:"channel-update", instruments:[], tags:["mmx #42","community","open source part"] },
  "f-zdCoI3tv8": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #43","progress","journey"] },
  "3v5xfWkp9Ys": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["mmx #44","bistable mechanism"] },
  "g8yWw4yN_yc": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble divider"], tags:["mmx #45","marble divider","success"] },
  "rMAVajTZHCs": { project:"Marble Machine X", videoType:"build-log", instruments:["flywheel"], tags:["mmx #46","flywheel"] },
  "QzjRB-RaB9w": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #47","top metal frame","assembly"] },
  "y0JFQY2kh4A": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #48","precision"] },
  "cu-mHxzOwVo": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #49","crank handle","no lathe"] },
  "0FzAvSdjuds": { project:"Marble Machine X", videoType:"workshop-tour", instruments:[], tags:["mmx #50","workshop tour","build team"] },
  "F6Z-yW4buh0": { project:"Marble Machine X", videoType:"build-log", instruments:["muting system","vibraphone"], tags:["mmx #51","muting levers","new parts"] },
  "vIrX81SVwnQ": { project:"Marble Machine X", videoType:"channel-update", instruments:[], tags:["mmx","mystery box","announcement"] },
  "tN7aI_HbAeU": { project:"Other", videoType:"channel-update", instruments:[], tags:["dearmoon","spacex","maezawa","moon"] },
  "KDBuUft_HSA": { project:"Other", videoType:"channel-update", instruments:[], tags:["quick announcement"] },
  "dNv8AeZfuUc": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble divider"], tags:["mmx #52","dropping ball","precisely"] },
  "CWG5oZB593w": { project:"Marble Machine X", videoType:"build-log", instruments:["marble divider"], tags:["mmx #53","marble divider","completion"] },
  "siZDYyn0_P8": { project:"Marble Machine X", videoType:"channel-update", instruments:[], tags:["mmx #54","community","help","funding"] },
  "cu12qeVML9E": { project:"Marble Machine X", videoType:"prototype-test", instruments:["rhythm machine","drums"], tags:["mmx #55","rhythm machine","mechanical"] },
  "OKwt2axN6OA": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #56","fusion 360","new parts design"] },
  "zVyEsMiwvVc": { project:"Marble Machine X", videoType:"educational", instruments:[], tags:["mmx #57","PBS system","project organisation"] },
  "JZuNOVLL5Ho": { project:"Marble Machine X", videoType:"build-log", instruments:["marble lift","gears"], tags:["mmx #58","marble gear lift","entrance"] },
  "3suNdUIOH30": { project:"Marble Machine X", videoType:"build-log", instruments:["programming wheel"], tags:["mmx #59","music programming plates"] },
  "93OjIcpNuWY": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates","magnets"], tags:["mmx #60","magnet polarity switch"] },
  "Z7g5ZodD7ng": { project:"Marble Machine X", videoType:"prototype-test", instruments:["conveyor belt"], tags:["mmx #61","conveyor belt","v2"] },
  "g_h9CaUDHoU": { project:"Marble Machine X", videoType:"build-log", instruments:["marble demagnetizer"], tags:["mmx #62","marble demagnetizer","v3"] },
  "dFqF1pDH_5Q": { project:"Marble Machine X", videoType:"behind-the-scenes", instruments:[], tags:["mmx #63","engineering team","2019"] },
  "7uw4HyfqkMA": { project:"Marble Machine X", videoType:"prototype-test", instruments:["vibraphone"], tags:["mmx #64","vibraphone","movement test"] },
  "AOKg8aY2FRU": { project:"Marble Machine X", videoType:"build-log", instruments:["programming wheel"], tags:["mmx #65","music programming plates","part 3"] },
  "lWUIK6-tUJY": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #66","rabbit hole","deep dive"] },
  "YK5Jcna7a_g": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #67","slaying the dragon"] },
  "AHendYjLFao": { project:"Marble Machine X", videoType:"build-log", instruments:["marble tracks","marble divider"], tags:["mmx #68","marble divider","transport tracks"] },
  "OoT1Gso8P1Q": { project:"Marble Machine X", videoType:"build-log", instruments:["marble gates"], tags:["mmx #69","marble release","pivot arms"] },
  "SGxh4oqr5Fk": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #70","instrument dummy","assembly"] },
  "pzyhiDvn0fU": { project:"Marble Machine X", videoType:"build-log", instruments:["drums"], tags:["mmx #71","drum bodies"] },
  "0zKdPjd1UeY": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #72","cross bracing","frame"] },
  "DAWgjSTjreI": { project:"Marble Machine X", videoType:"prototype-test", instruments:["sizzle cymbal"], tags:["mmx #73","sizzle cymbal","soundcheck"] },
  "KijBavuFS28": { project:"Marble Machine X", videoType:"prototype-test", instruments:["kick drum"], tags:["mmx #74","kick drum","soundcheck"] },
  "gWxjIviyPQI": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #75","TIG welding","marathon"] },
  "27ZMQa6W9OU": { project:"Marble Machine X", videoType:"educational", instruments:[], tags:["mmx #76","CNC","complex shapes"] },
  "CBfd0Tjii9Y": { project:"Marble Machine X", videoType:"prototype-test", instruments:["clutch","timing"], tags:["mmx #77","timing clutch","music timing"] },
  "1AEvQAg6TE0": { project:"Marble Machine X", videoType:"build-log", instruments:["conveyor belt"], tags:["mmx #78","conveyor belt","completed"] },
  "Uid4N1EbXRY": { project:"Marble Machine X", videoType:"educational", instruments:[], tags:["mmx #79","acrylic pipe","bending"] },
  "WmMWkd-7Q8A": { project:"Marble Machine X", videoType:"prototype-test", instruments:["snare drum"], tags:["mmx #80","snare drum","experiments"] },
  "kt8K4giKny8": { project:"Marble Machine X", videoType:"build-log", instruments:["pedal","flywheel"], tags:["mmx #81","treadle pedal","completed"] },
  "D6Un2CQxONE": { project:"Marble Machine X", videoType:"prototype-test", instruments:["bass"], tags:["mmx #82","kinetic fingers","bass","prototype"] },
  "QbqC9C6UEck": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #83","instrument support","assembly"] },
  "w6TzpE2fTMM": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #84","tweaks","fixes"] },
  "d4tpRFoLXbw": { project:"Marble Machine X", videoType:"build-log", instruments:["marble loop"], tags:["mmx #85","marble loop","completed"] },
  "isosWOzmbe0": { project:"Marble Machine X", videoType:"prototype-test", instruments:["drums","kick drum","sizzle cymbal"], tags:["mmx #86","plays drums","first test"] },
  "_dhQeBBNCtc": { project:"Other", videoType:"channel-update", instruments:[], tags:["summer break","channel update"] },
  "F-RYfQKnlt4": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble funnel"], tags:["mmx #87","marble funnel","design test"] },
  "wZ5gcMKJujM": { project:"Marble Machine X", videoType:"prototype-test", instruments:["vibraphone"], tags:["mmx #88","vibraphone","design test"] },
  "RuruLb5YcPE": { project:"Marble Machine X", videoType:"prototype-test", instruments:["vibraphone","marble divider"], tags:["mmx #89","38 magic number","vibraphone"] },
  "OAZ3pVSCYSQ": { project:"Marble Machine X", videoType:"prototype-test", instruments:["flywheel"], tags:["mmx #90","flywheel","torque limiter"] },
  "joqxfIbH2eE": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["mmx #91","marble gates","design"] },
  "JpQLHbLmo68": { project:"Marble Machine X", videoType:"build-log", instruments:["sizzle cymbal","damper"], tags:["mmx #92","one day build","cymbal hitter","damper"] },
  "FqvDmWUUgNA": { project:"Marble Machine X", videoType:"build-log", instruments:["vibraphone"], tags:["mmx #93","vibraphone bar holders"] },
  "9K_ZWogCA9Q": { project:"Marble Machine X", videoType:"prototype-test", instruments:["vibraphone"], tags:["mmx #94","vibraphone","sustain control"] },
  "qJz95Wm0_Ck": { project:"Marble Machine X", videoType:"prototype-test", instruments:["vibraphone"], tags:["mmx #95","liquid latex","sound fix","vibraphone"] },
  "6J2fGtFXlGQ": { project:"Marble Machine X", videoType:"prototype-test", instruments:["vibraphone"], tags:["mmx #96","vibraphone","microphone","experiments"] },
  "NyRJaVOIgYU": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #97","3D printed metal","polishing"] },
  "hrEpIgIEUnU": { project:"Marble Machine X", videoType:"prototype-test", instruments:["sizzle cymbal"], tags:["mmx #98","cymbal","marble drop"] },
  "A1wr3Rqxjy4": { project:"Marble Machine X", videoType:"prototype-test", instruments:["vibraphone"], tags:["mmx #99","vibraphone","marble drops"] },
  "JgM2ruB8M34": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #100","CNC","plywood parts"] },
  "0v0cewf26Po": { project:"Marble Machine X", videoType:"prototype-test", instruments:["vibraphone"], tags:["mmx #101","harmonics jig","sweetspot","vibraphone"] },
  "BrFYow6_aw4": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #102","best design"] },
  "uay5GKmueaI": { project:"Marble Machine X", videoType:"prototype-test", instruments:["vibraphone"], tags:["mmx #103","vibraphone","height adjustment"] },
  "cGeTp-3KUr4": { project:"Marble Machine X", videoType:"prototype-test", instruments:["vibraphone","vibrato"], tags:["mmx #104","vibrato","experiments","vibraphone"] },
  "tVbh_FEiF2E": { project:"Marble Machine X", videoType:"prototype-test", instruments:["vibraphone"], tags:["mmx #105","la valse d'amelie","vibraphone","melody test"] },
  "Bc3tBADGnlg": { project:"Marble Machine X", videoType:"prototype-test", instruments:["snare drum"], tags:["mmx #106","snare drum","dream sound"] },
  "oCt59XHdeZM": { project:"Marble Machine X", videoType:"prototype-test", instruments:["rhythm machine","drums"], tags:["mmx #107","rhythm machine","experiments"] },
  "yfEqotNhL6o": { project:"Marble Machine X", videoType:"prototype-test", instruments:["hi-hat"], tags:["mmx #108","hi-hat machine","prototype"] },
  "4KtSKT-EqLo": { project:"Marble Machine X", videoType:"prototype-test", instruments:["bass"], tags:["mmx #109","custom bass guitar"] },
  "b2RAJNZYBYw": { project:"Marble Machine X", videoType:"prototype-test", instruments:["bass"], tags:["mmx #110","bass strings","marbles","striking"] },
  "-rXv0hMndeQ": { project:"Other", videoType:"prototype-test", instruments:["ondophone"], tags:["mmx #111","ondophone","new instrument","wind","electrostatic"] },
  "B2OmoQ_UH_g": { project:"Marble Machine X", videoType:"educational", instruments:["muting system","vibraphone"], tags:["mmx #112","muting system","how it works"] },
  "_YzgfBtyqAU": { project:"Other", videoType:"build-log", instruments:["guitar"], tags:["guitar","renovation","instrument repair"] },
  "wRwNnHjAo3k": { project:"Other", videoType:"philosophical", instruments:[], tags:["attention","time","focus","philosophy"] },
  "z8HBiUiYTjo": { project:"Speelklok", videoType:"inspiration", instruments:["banjo"], tags:["self-playing banjo","inspiration","mmx"] },
  "iXXYLEWpJwQ": { project:"Other", videoType:"channel-update", instruments:[], tags:["2020 plans","channel update","wintergatan wednesdays"] },

  // ── MMX late build (2020) ────────────────────────────────────────────────
  "EzdEudvpbrg": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #113","new parts","workbench","fresh start"] },
  "NQU22mn8h_M": { project:"Marble Machine X", videoType:"prototype-test", instruments:["motor","flywheel"], tags:["mmx #114","electric motor","flywheel"] },
  "TIoY3C2z9o4": { project:"Marble Machine X", videoType:"prototype-test", instruments:["timing"], tags:["mmx #115","tight music","timing"] },
  "6qcz4tmD5bQ": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble loop"], tags:["mmx #116","marble catcher","marble loop"] },
  "vR25TPPpGVg": { project:"Cyber Bass", videoType:"prototype-test", instruments:["bass","cyber bass"], tags:["cyber bass","bass","marble drops","first play"] },
  "owWX5ZJapMw": { project:"Marble Machine X", videoType:"channel-update", instruments:[], tags:["marble race","marble machine x","fun"] },
  "MCPPOCrWpU0": { project:"Other", videoType:"build-log", instruments:[], tags:["acoustic panels","plywood","music studio","acoustics"] },
  "rvL83-iy-EQ": { project:"Cyber Bass", videoType:"prototype-test", instruments:["bass","cyber bass"], tags:["cyber bass","marble drops"] },
  "l09IVjZXjEU": { project:"Cyber Bass", videoType:"prototype-test", instruments:["marble funnel","cyber bass"], tags:["cyber funnel","marble funnel","cyber bass"] },
  "eLUDauIxudM": { project:"Other", videoType:"philosophical", instruments:[], tags:["focus","goals","productivity","philosophy"] },
  "UjcMyfcVPvI": { project:"Marble Machine X", videoType:"build-log", instruments:["vibraphone","marble funnel"], tags:["mmx","vibraphone funnels","completed"] },
  "BFUW_7n3O0k": { project:"Cyber Bass", videoType:"prototype-test", instruments:["bass","cyber bass"], tags:["cyber bass","capos","bass strings"] },
  "dMxQO4xDGfg": { project:"Other", videoType:"channel-update", instruments:[], tags:["community","engagement","wintergatan"] },
  "C1LlaPFN80g": { project:"Marble Machine X", videoType:"channel-update", instruments:[], tags:["109 things to do","mmx","list"] },
  "CKTa5yHfsxI": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #127","music studio","acoustic measurements"] },
  "Y19FucqIZ3A": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #128","music studio","dream studio","step 1"] },
  "be44AgtJgX8": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble funnel"], tags:["mmx #129","marble funnels","rubber coating"] },
  "K4RkqOcU3Cs": { project:"Marble Machine X", videoType:"build-log", instruments:["conveyor belt"], tags:["mmx #130","conveyor belt","repair"] },
  "SHi4LLSJuxo": { project:"Marble Machine X", videoType:"build-log", instruments:["marble demagnetizer"], tags:["mmx #131","marble demagnetizer","2.0"] },
  "b-nU21YgXTg": { project:"Marble Machine X", videoType:"build-log", instruments:["marble tracks"], tags:["mmx #132","marble tracks","completed"] },
  "Ygofdm9JB3g": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #133","28 audio channels","single cable"] },
  "4JiBxVxJzJE": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #134","feels like home"] },
  "5bIVBqBHuOQ": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble funnel"], tags:["mmx #135","candy dip","marble funnels"] },
  "YqWApMqD4h4": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble divider"], tags:["mmx #136","marble divider","redesign"] },
  "UENil4T8mXM": { project:"Cyber Bass", videoType:"prototype-test", instruments:["bass","cyber bass"], tags:["mmx #137","cyber bass","rubber wheels"] },
  "NEZFnnAb02g": { project:"Marble Machine X", videoType:"build-log", instruments:["hi-hat"], tags:["mmx #138","hi-hat machine","end stops"] },
  "Abaox9MzSHg": { project:"Marble Machine X", videoType:"channel-update", instruments:[], tags:["mmx","plan for completion","transition to music"] },
  "UYFdNwXXcac": { project:"Marble Machine X", videoType:"prototype-test", instruments:[], tags:["mmx #139","marble module","CAD team"] },
  "l8hUY6-LSws": { project:"Other", videoType:"philosophical", instruments:[], tags:["workspace organisation","triforce","philosophy"] },
  "AqLRMMPuCeI": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #140","new parts","quick update"] },
  "F9wiCalUvVY": { project:"Marble Machine X", videoType:"build-log", instruments:["marble gates"], tags:["mmx #141","spring tension mechanism"] },
  "M4jwmAB3wpM": { project:"Marble Machine X", videoType:"philosophical", instruments:[], tags:["mmx #142","rebuild","why","philosophy"] },
  "8KyoZiU0MaY": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["mmx #143","countersink","why"] },
  "qlsVZr52CFw": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["mmx #144","marble gates","better design"] },
  "5I2Am0UCCpo": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["mmx #145","marble gates","5000 marbles","test"] },
  "CIsx5izE170": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["mmx #146","10000 marbles","accuracy"] },
  "M6T6CSiJv-A": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["mmx #147","20000 marbles","accuracy"] },
  "ZI2Q5cFqx9k": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["mmx #148","30000 marbles","accuracy"] },
  "e1BYAfrUwLk": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["mmx #149","50000 marbles","accuracy"] },

  // ── MMX marble gate iteration (2021) ────────────────────────────────────
  "bCrDDXTPp0s": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble tracks"], tags:["marble track comparison","which is best"] },
  "m2nzDJzRqis": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble tracks"], tags:["marble track","testing another"] },
  "jtiZf_pK1Do": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["zig-zag marble gate","completed"] },
  "JM9ZeO36954": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates","escapement"], tags:["clock escapement","marble gate"] },
  "WznroG2VtxU": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble funnel"], tags:["laser cut","marble funnels"] },
  "pyf_T-rhVK8": { project:"Other", videoType:"educational", instruments:[], tags:["engineering basics","best part is no part","simplify"] },
  "GBWXzLfkKLI": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["material showdown","marble gates"] },
  "ESgpTh7zQ5I": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble divider"], tags:["new marble divider","test"] },
  "UwXdzWaujJY": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble divider"], tags:["new marble divider","success"] },
  "neuULfh5ApI": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble tracks"], tags:["marble tracks","hidden feature"] },
  "Jh6c7OpANNY": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["pinball machine","marble gate","simplest"] },
  "U4B0i0VzXuA": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble divider"], tags:["marble divide by 4","simplest design"] },
  "J-JNndmXC8Q": { project:"Marble Machine X", videoType:"build-log", instruments:["marble gates"], tags:["marble gate attachments","waterjet cutting"] },
  "pAHYTP1-fQY": { project:"Cyber Bass", videoType:"build-log", instruments:["bass","marble gates"], tags:["cyberbass","pacman gates","waterjet cutting"] },
  "Ri7yYM1CV2E": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates","escapement"], tags:["clock escapement","marble gate","silent design"] },
  "Z-KeJj8BuJ0": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["cybergates","marble gates"] },
  "3EZs3YpdKuU": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble loop"], tags:["marble loop forever","loop test"] },
  "b0kzTgz-y4Y": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["99% not enough","accuracy test"] },
  "6Yk3d5S8QTE": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates","escapement"], tags:["escapement gates","make it or break it","part 1"] },
  "Jnx7vAMvssI": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["1000 pieces","engineering puzzle"] },
  "fUkEEckuf0o": { project:"Marble Machine X", videoType:"build-log", instruments:["marble gates"], tags:["brass wheels","marble gates"] },
  "PJq3su_UTCs": { project:"Marble Machine X", videoType:"build-log", instruments:["marble gates"], tags:["silver steel axles","escapement gates"] },
  "UKvqC3t-M1g": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["marble gate test","will it work"] },
  "0b-B_Bg31Zg": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["10000 marbles","accuracy test"] },
  "-gPVvoIEw0w": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["30000 marbles","accuracy test"] },

  // ── Cyber Bass live assembly series ─────────────────────────────────────
  "eyDkJ0-V19I": { project:"Cyber Bass", videoType:"build-log", instruments:["bass","cyber bass"], tags:["cyberbass","marble drops","live assembly","part 1"] },
  "Y7SjDmnUtus": { project:"Cyber Bass", videoType:"build-log", instruments:["bass","cyber bass"], tags:["cyberbass","marble drops","live assembly","part 2"] },
  "X_DlsgjVyno": { project:"Cyber Bass", videoType:"build-log", instruments:["bass","cyber bass"], tags:["cyberbass","marble drops","live assembly","part 3"] },
  "GDdZVItbN-E": { project:"Cyber Bass", videoType:"build-log", instruments:["bass","cyber bass"], tags:["cyberbass","marble drops","live assembly","part 4"] },
  "p46nM2QGGSo": { project:"Cyber Bass", videoType:"prototype-test", instruments:["bass","cyber bass"], tags:["cyberbass","marble drops","bench test","part 5"] },
  "YyG8s2bzxKU": { project:"Cyber Bass", videoType:"build-log", instruments:["bass","cyber bass"], tags:["cyberbass","marble drops","welding bracket","part 6"] },
  "1IrKFS0Wtnw": { project:"Cyber Bass", videoType:"prototype-test", instruments:["bass","cyber bass"], tags:["cyberbass testing","marble machine x live"] },
  "TCDliGXBW64": { project:"Cyber Bass", videoType:"prototype-test", instruments:["bass","cyber bass"], tags:["cyberbass testing","part 2","marble machine x live"] },
  "I-SZ2gggQEE": { project:"Cyber Bass", videoType:"prototype-test", instruments:["bass","cyber bass"], tags:["cyberbass","8 channel drop test","marble machine x live"] },
  "GHr4ZnWreWI": { project:"Cyber Bass", videoType:"prototype-test", instruments:["bass","cyber bass","timing"], tags:["cyberbass timing test","marble machine x live"] },
  "_JLOasfa-uc": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["60000 marbles","live test"] },
  "-kSkeqVPC6I": { project:"Marble Machine X", videoType:"build-log", instruments:["drums"], tags:["drum triggers","installation"] },
  "I3Rg7SdIPoE": { project:"Marble Machine X", videoType:"build-log", instruments:["kick drum","marble gates"], tags:["kick drum marble gate","making"] },
  "ZddqSR1wXkE": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["80000 marbles","live test"] },
  "TbQWgePDLTU": { project:"Other", videoType:"channel-update", instruments:[], tags:["summer 2021","channel update"] },
  "WN90HYiFpAw": { project:"Marble Machine X", videoType:"philosophical", instruments:[], tags:["mmx","dumb design","lesson","retrospective"] },

  // ── Martin vs The Machine (2022) ─────────────────────────────────────────
  "V_n4HKLGnG4": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["martin vs the machine","round 3","week 1"] },
  "HXa6HHZu8uc": { project:"Marble Machine X", videoType:"build-log", instruments:["programming wheel"], tags:["martin vs the machine","week 2","music programming"] },
  "tbiQHxpwtOo": { project:"Other", videoType:"educational", instruments:[], tags:["decision matrix","decision making","engineering"] },
  "sPR_mzNu7lY": { project:"Marble Machine X", videoType:"build-log", instruments:[], tags:["martin vs the machine","week 4"] },
  "U7rsI37qFec": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates","bowden cable"], tags:["martin vs the machine","week 5","bowden cable","marble gate"] },
  "0BB4Y_OuBUQ": { project:"Other", videoType:"workshop-tour", instruments:[], tags:["new music studio","moving from france","workshop"] },

  // ── MMX marble gate research (late 2022) ────────────────────────────────
  "VyIk0IqC7SQ": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["arduino","marble gate","electronics"] },
  "lC_oLb1pfqU": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["marble gate","surprising result"] },
  "Nal8Q0fG4qk": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["marble gate","precision test"] },
  "qu-6wawAZ0U": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["marble experiment","success"] },
  "IPxs7T6iY10": { project:"Marble Machine X", videoType:"prototype-test", instruments:["marble gates"], tags:["foolproof marble gate","design"] },
  "TEKZWiKelCU": { project:"Other", videoType:"educational", instruments:[], tags:["design trick","engineering","technique"] },

  // ── Marble Machine 3 era (2023) ──────────────────────────────────────────
  "1FFTaI__l_A": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["programming wheel"], tags:["mm3","music programming pin","new design"] },
  "AEbqvrLkvbA": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["programming wheel"], tags:["mm3","music programming wheel"] },
  "VFygF-xDkzk": { project:"Other", videoType:"educational", instruments:[], tags:["airplane design","inspiration","engineering"] },
  "OFFGQqNQV1M": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["gears","timing"], tags:["mm3","gears","tighter music"] },
  "RGh8XVB8y9k": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["programming wheel"], tags:["mm3","music reader","new design"] },
  "Ub7AF3dH6i0": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["marble gates","bowden cable"], tags:["mm3","bowden cables","surprising"] },
  "nEZ7QFKDp0k": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["marble gates","bowden cable","timing"], tags:["mm3","bowden cables","tight music"] },
  "z-g3YXc6nXY": { project:"Marble Machine X", videoType:"channel-update", instruments:[], tags:["mmx","back from dead","revival","channel update"] },
  "eTOX0124OUc": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["clutch"], tags:["mm3","marble powered clutch","safety"] },
  "jPuJGW7Nuzo": { project:"Music Box", videoType:"channel-update", instruments:[], tags:["wintergatan music box","speldosa","VST","release"] },
  "8inFbhsIbBc": { project:"Music Box", videoType:"educational", instruments:[], tags:["speldosa","VST","AU","sounds","tutorial"] },
  "JJir3aAeBlg": { project:"Music Box", videoType:"educational", instruments:[], tags:["music box plugins","comparison","speldosa"] },
  "8CJuP96OFcA": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["marble gates"], tags:["mm3 ep.1","marbles","dynamic sound","material test"] },
  "s2ZqwihXqF4": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["bearings","flywheel"], tags:["mm3 ep.2","cheap bearing housing"] },
  "pEAC83q86v4": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["bearings","flywheel"], tags:["mm3 ep.3","worst bearing housing","fail"] },
  "Mzhaz7WsJ-A": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["flywheel"], tags:["mm3 ep.4","better flywheel","design"] },
  "4Q88W2MT60s": { project:"Marble Machine 3", videoType:"build-log", instruments:["flywheel","pedal"], tags:["mm3 ep.5","power module","completed"] },
  "HKmjtQd8NwQ": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["gears","lego"], tags:["mm3 ep.6","lego","music experiment","amazing result"] },
  "MG3DBTPM_XU": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["gears","lego"], tags:["mm3","lego technic","huygens chain drive"] },
  "D_YLF0ADuAI": { project:"Marble Machine 3", videoType:"build-log", instruments:[], tags:["mm3","taking shape","progress"] },

  // ── Flywheel prototype 11-day sprint (Aug 2023) ──────────────────────────
  "fgwLG4M8TEY": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["flywheel"], tags:["mm3","flywheel prototype","day 1"] },
  "zxKLo6Wjfwg": { project:"Marble Machine 3", videoType:"build-log", instruments:["flywheel"], tags:["mm3","flywheel prototype","day 2","lathe","metal turning"] },
  "MB7CNIIt9CA": { project:"Marble Machine 3", videoType:"build-log", instruments:["flywheel"], tags:["mm3","flywheel prototype","day 3","welding frame"] },
  "3MRKXjGbGQA": { project:"Marble Machine 3", videoType:"build-log", instruments:["flywheel","pedal"], tags:["mm3","flywheel prototype","day 4","pedal connected"] },
  "IYEezqWtBkA": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["timing"], tags:["mm3","flywheel prototype","day 5","music timing","clock"] },
  "p21xT8_DV00": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["flywheel","timing"], tags:["mm3","flywheel prototype","day 6","first timing tests"] },
  "Ra1_wpgmaUE": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["flywheel"], tags:["mm3","flywheel prototype","day 7-9","wobbly flywheel"] },
  "MDJu3FLDc54": { project:"Marble Machine 3", videoType:"build-log", instruments:["flywheel"], tags:["mm3","flywheel prototype","day 10","finished"] },
  "kcVazO0ODuw": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["flywheel","timing"], tags:["mm3","flywheel prototype","day 11","heavy flywheel","tighter music"] },
  "9X2J8JN9g-k": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["flywheel","timing"], tags:["mm3","faster flywheel","tighter music"] },
  "ITJeMnJ2HaU": { project:"Other", videoType:"educational", instruments:[], tags:["gravity","constant","experiment","physics"] },
  "NO-BgMiC2yg": { project:"Other", videoType:"educational", instruments:["bearings"], tags:["SKF","bearing selection","8 step method","engineering"] },
  "gPyZSX71np8": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["flywheel","timing"], tags:["mm3","gravity","tight music"] },
  "18ZSKRhOLS8": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["marble divider"], tags:["mm3","mystery marble divider"] },
  "COgY3mI0Yzg": { project:"Other", videoType:"build-log", instruments:["guitar"], tags:["custom fingerboard","guitar","collaboration","swepudding"] },
  "qHho5auQBFM": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["programming wheel"], tags:["mm3","programming wheel","prototyping"] },
  "ITCEhEHM5QU": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["timing","marble gates"], tags:["mm3","marbles","tight music"] },
  "Y83I8mLKufo": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["marble divider"], tags:["mm3","holy grail marble divider","breakthrough"] },
  "jJkoZgKVEx8": { project:"Marble Machine 3", videoType:"educational", instruments:["flyball governor","timing"], tags:["mm3","gramophone","flyball governor","tight music"] },
  "xTYnwKxlLIQ": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["vibraphone"], tags:["mm3","steel marbles","metal vibraphone","sound test"] },
  "i63t7ekNFoY": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["flyball governor"], tags:["mm3","130 year old solution","flyball governor"] },
  "rVCF8wjwj2E": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["kick drum"], tags:["mm3","big marble","kick drum","sound test"] },
  "8ouH21npL58": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["programming wheel","timing"], tags:["mm3","faster wheel","tighter music"] },
  "hUGOrvWRf5Y": { project:"Marble Machine 3", videoType:"philosophical", instruments:[], tags:["mm3","10 meter wide","concept","scale"] },
  "qjkIMxmSeIc": { project:"Marble Machine 3", videoType:"prototype-test", instruments:[], tags:["mm3","annoying problem","mmx fix"] },
  "M337IV9dSuk": { project:"Marble Machine 3", videoType:"channel-update", instruments:[], tags:["mm3","plan to finish","community","patreon"] },
  "s2qKe4Ohx00": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["gears"], tags:["mm3","gear types","efficiency"] },
  "BpJYqC4PWEw": { project:"Other", videoType:"philosophical", instruments:[], tags:["why","motivation","marble machine project","philosophy"] },
  "AbmMnu-NpaI": { project:"Marble Machine 3", videoType:"build-log", instruments:[], tags:["mm3","45 degree angles","coming to life"] },
  "JadbqfeZ09M": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["bass"], tags:["mm3","bass","marbles","3 new ideas"] },
  "P0KPHNbkWPU": { project:"Marble Machine 3", videoType:"build-log", instruments:[], tags:["mm3","shape","design evolution"] },
  "J0T8sDdDC08": { project:"Marble Machine 3", videoType:"educational", instruments:["bass"], tags:["mm3","mechanical fingers","bass","why"] },
  "gbuWJ48T0bE": { project:"Other", videoType:"educational", instruments:[], tags:["design process","planning","pixar","storytelling"] },
  "ievnZAamJD0": { project:"Other", videoType:"philosophical", instruments:[], tags:["power of why","design philosophy"] },
  "svMh5KRvGKQ": { project:"Marble Machine 3", videoType:"prototype-test", instruments:[], tags:["mm3","cardboard model","prototyping"] },
  "GNmL6tFsrvc": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["programming wheel"], tags:["mm3","song switching","new mechanism"] },
  "urfP4xrpn9M": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["crash cymbal"], tags:["mm3","steel ball","crash cymbal","sound test"] },
  "Q8ZxMlCSpWw": { project:"Other", videoType:"philosophical", instruments:[], tags:["find the magic","creativity","philosophy"] },
  "-doY1Q73B6Y": { project:"Marble Machine 3", videoType:"educational", instruments:["flywheel"], tags:["mm3","moment of inertia","flywheel","physics"] },
  "Vs-0ij4oviM": { project:"Marble Machine 3", videoType:"build-log", instruments:[], tags:["mm3","drivetrain","design"] },
  "RgkhBX0Lxds": { project:"Marble Machine 3", videoType:"philosophical", instruments:[], tags:["mm3","identity","what it is","concept"] },
  "07b9leapeLc": { project:"Marble Machine 3", videoType:"educational", instruments:[], tags:["mm3","text document","planning","requirements"] },

  // ── Animusic / percussion tangents (late 2024) ───────────────────────────
  "KuKYu3GIxYc": { project:"Other", videoType:"prototype-test", instruments:["tambourine","percussion"], tags:["mechanical tambourine","forbidden song","prototype"] },
  "Kw6bmac63-s": { project:"Other", videoType:"prototype-test", instruments:["drums","percussion"], tags:["percussion machine","human feel","prototype"] },
  "gRSdwgt5jFg": { project:"Other", videoType:"prototype-test", instruments:["percussion"], tags:["animated percussion","animusic","pipe dream","tribute"] },
  "grp5FjlxHIY": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["drums","snare drum"], tags:["mm3","marbles","drum roll","test"] },
  "3hsZyi72CBg": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["drums"], tags:["mm3","drums that move","fun","kinetic"] },
  "QMgVt3OJbrU": { project:"Other", videoType:"music", instruments:["percussion"], tags:["animusic","future retro","cover","marbles"] },
  "Vg6sG3frJ18": { project:"Marble Machine X", videoType:"philosophical", instruments:[], tags:["monster music box","mmx","retrospective","music box"] },
  "HSfBYRLo0p4": { project:"Wintergatan Band", videoType:"music", instruments:["other"], tags:["emerson","2011","demo","early wintergatan"] },
  "0HXteCccHUI": { project:"Music Box", videoType:"music", instruments:["other"], tags:["harry potter","theme","music box"] },
  "k8NXF2rtaEg": { project:"Marble Machine 3", videoType:"philosophical", instruments:[], tags:["mm3","leonardo da vinci","inspiration","design"] },

  // ── Gear breakthrough & MM3 acceleration (2025) ─────────────────────────
  "zVojuK_CXJM": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["gears"], tags:["mm3","perfect gears","8 years","breakthrough"] },
  "4fcjpnWd8co": { project:"Marble Machine 3", videoType:"prototype-test", instruments:[], tags:["mm3","solved it","8 years","breakthrough"] },
  "V0H6ChgRe44": { project:"Marble Machine 3", videoType:"educational", instruments:["gears"], tags:["mm3","one-way bearings","mechanical magic"] },
  "j7jGokLIOqI": { project:"Marble Machine 3", videoType:"educational", instruments:["timing","gears"], tags:["mm3","better music","timing","why"] },
  "3_vRx0h9np4": { project:"Marble Machine 3", videoType:"prototype-test", instruments:[], tags:["mm3","simple idea","changed marble music","breakthrough"] },
  "a5tDU8UkMcI": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["600 year old clock tower","marble machine song","city","museum"] },
  "RmrHewtm6yQ": { project:"Marble Machine 3", videoType:"channel-update", instruments:[], tags:["mm3","what does mm3 do","update"] },
  "MMcQuPR5UHw": { project:"Marble Machine 3", videoType:"prototype-test", instruments:[], tags:["mm3","simplest idea","breakthrough"] },
  "Jt82D7uW4OA": { project:"Marble Machine 3", videoType:"build-log", instruments:["gears"], tags:["mm3","largest plywood gears","how to make"] },
  "v3q7IMXC-Hk": { project:"Marble Machine 3", videoType:"build-log", instruments:["gears"], tags:["mm3","double helical","plywood gears","plan"] },
  "pXJcdd8SZ1c": { project:"Marble Machine", videoType:"music", instruments:["vibraphone","bass","sizzle cymbal"], tags:["marble machine","music with 2000 marbles","repost"] },
  "RikB-LvD-v0": { project:"Other", videoType:"music", instruments:["other"], tags:["modulin","mega man","homemade instrument"] },
  "ZmY2dtb-6E4": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["gears","vibraphone"], tags:["mm3","marbles and gears","amelie","theme song","test"] },
  "orit6xyFBQw": { project:"Speelklok", videoType:"inspiration", instruments:["violin"], tags:["self-playing violin","magic","museum"] },
  "H1zuubXzj4k": { project:"Other", videoType:"music", instruments:["musical saw"], tags:["harry potter","musical saw","forbidden"] },
  "aVtV3AEZUA4": { project:"Other", videoType:"music", instruments:["other"], tags:["forbidden song","spontaneous","fun"] },
  "254IjOwkpg8": { project:"Other", videoType:"educational", instruments:[], tags:["modulin","synth","violin","homemade instrument","how it works"] },
  "CyDm7XqMN3s": { project:"Music Box", videoType:"educational", instruments:["lego"], tags:["music box","lego","why","building"] },
  "MYgiOD9-TQo": { project:"Marble Machine", videoType:"music", instruments:["other"], tags:["marble machine","piano version","cover"] },
  "338AAXTgpZQ": { project:"Other", videoType:"philosophical", instruments:[], tags:["good design","design philosophy","what is good design"] },
  "dNlZ2NO5vg8": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["marble divider"], tags:["mm3","perfect marble divider","improved"] },
  "wtFLaX4KZTs": { project:"Other", videoType:"music", instruments:["other"], tags:["piano","boat","spontaneous","fun"] },
  "YV92xwyV5sg": { project:"Marble Machine 3", videoType:"music", instruments:["gears","vibraphone"], tags:["mm3","marbles playing animusic","music demo"] },
  "iwWeuoqXmyM": { project:"Speelklok", videoType:"music", instruments:["other"], tags:["500 year old instrument","improvised","carillon","museum"] },
  "yyvQafTwBMI": { project:"Music Box", videoType:"educational", instruments:[], tags:["how to program a music box","tutorial"] },

  // ── Marble Machine 3 first real parts (mid–late 2025) ───────────────────
  "ofFNGoSFKOI": { project:"Marble Machine 3", videoType:"build-log", instruments:[], tags:["mm3","first real parts","milestone"] },
  "k2i8FXIExU8": { project:"Marble Machine 3", videoType:"build-log", instruments:[], tags:["mm3","first parts","overview"] },
  "rFweD91GEcA": { project:"Marble Machine 3", videoType:"philosophical", instruments:[], tags:["mm3","simple idea","rescued","philosophy"] },
  "BJuNx2paXKE": { project:"Other", videoType:"channel-update", instruments:[], tags:["best day of my life","channel update","personal"] },
  "0NDxlBAFIJo": { project:"Marble Machine 3", videoType:"workshop-tour", instruments:[], tags:["mm3","workshop build"] },
  "GsAoMLky4NQ": { project:"Marble Machine 3", videoType:"workshop-tour", instruments:[], tags:["mm3","workshop transformation"] },

  // ── Marble Machine 3 live streams (2026) ─────────────────────────────────
  "sLYWINDOBFU": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["vibraphone"], tags:["mm3","3D printed silicone","vibraphone holder","new material"] },
  "tjBjvL6sNBc": { project:"Marble Machine 3", videoType:"prototype-test", instruments:[], tags:["mm3","small fix","sound difference"] },
  "Pq4NOi7KGgI": { project:"Marble Machine 3", videoType:"build-log", instruments:["gears"], tags:["mm3","largest plywood gear","build"] },
  "V-K1I1FREXs": { project:"Marble Machine 3", videoType:"build-log", instruments:["gears"], tags:["mm3","largest plywood gear","build","duplicate"] },
  "WA1RGydNmSg": { project:"Marble Machine 3", videoType:"build-log", instruments:[], tags:["mm3","locking in","smarter marble machine"] },
  "RvfYrpEPTm8": { project:"Marble Machine 3", videoType:"build-log", instruments:[], tags:["mm3","smarter italian marble machine"] },
  "i582paB8kvQ": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["vibraphone"], tags:["mm3","vibraphone features","what matters most"] },
  "pwMmekWMdQU": { project:"Marble Machine 3", videoType:"philosophical", instruments:[], tags:["mm3","starting over","scratch again","pivot"] },
  "ATj41HxVveE": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["drums"], tags:["mm3","what drums does marble machine need"] },
  "KoIDLnxuxdg": { project:"Marble Machine 3", videoType:"prototype-test", instruments:[], tags:["mm3","marble size","choosing"] },
  "WReG2HweyMk": { project:"Marble Machine 3", videoType:"educational", instruments:[], tags:["mm3","onshape","master part method","CAD"] },
  "JZfyEAAwlkw": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["vibraphone"], tags:["mm3","vibraphone features","design requirements"] },
  "-Wq3qcR-xl0": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["drums"], tags:["mm3","finding right drums"] },
  "u-3lFCYFV_g": { project:"Marble Machine 3", videoType:"educational", instruments:[], tags:["mm3","onshape","5 key reasons","CAD switch"] },
  "oX8oy8UxvcE": { project:"Marble Machine 3", videoType:"prototype-test", instruments:[], tags:["mm3","marble size","choosing","duplicate"] },
  "66FDq5Um5Vg": { project:"Marble Machine 3", videoType:"build-log", instruments:["gears"], tags:["mm3","gear train","design"] },
  "FcDwMbyvGuY": { project:"Marble Machine 3", videoType:"live-stream", instruments:["gears"], tags:["mm3","drive train design","live","onshape"] },
  "MFVulAb99BI": { project:"Marble Machine 3", videoType:"live-stream", instruments:["gears"], tags:["mm3","drive train design","part 2","live","onshape"] },
  "u183vWMIws4": { project:"Marble Machine 3", videoType:"live-stream", instruments:["programming wheel"], tags:["mm3","programming wheel","master part","live","onshape"] },
  "7bHJHPfhrAA": { project:"Marble Machine 3", videoType:"live-stream", instruments:["flyball governor"], tags:["mm3","flyball governor","master part","live","onshape"] },
  "tyzO95hqev8": { project:"Marble Machine 3", videoType:"live-stream", instruments:[], tags:["mm3","master part model","onshape","live"] },
  "vU-b1fCE9t8": { project:"Marble Machine 3", videoType:"live-stream", instruments:[], tags:["mm3","master part model","onshape","live","part 2"] },
  "qPeMvyaMXgI": { project:"Marble Machine 3", videoType:"live-stream", instruments:["marble loop"], tags:["mm3","marble loop","master part","live","onshape"] },
  "xgIMW4lcbA4": { project:"Marble Machine 3", videoType:"live-stream", instruments:["marble loop"], tags:["mm3","marble loop","master part","live","onshape","part 2"] },
  "HmnCeb58MOo": { project:"Marble Machine 3", videoType:"live-stream", instruments:[], tags:["mm3","skeleton clock frame","master part","live","onshape"] },
  "5QWogxsE2SE": { project:"Marble Machine 3", videoType:"live-stream", instruments:[], tags:["mm3","controls","master part","live","onshape"] },
  "gRv1B8pp0Qg": { project:"Marble Machine 3", videoType:"build-log", instruments:[], tags:["mm3","real progress","weekly recap"] },
  "1AITDBHMuko": { project:"Marble Machine 3", videoType:"live-stream", instruments:[], tags:["mm3","design requirements","learning to love","live"] },
  "QZbMQwymSMs": { project:"Marble Machine 3", videoType:"live-stream", instruments:[], tags:["mm3","design requirements","learning to love","live","part 2"] },
  "3YnTfSZMHBk": { project:"Marble Machine 3", videoType:"live-stream", instruments:["vibraphone"], tags:["mm3","vibraphone plates","should they move","live"] },
  "qPZ5k6UHke0": { project:"Marble Machine 3", videoType:"educational", instruments:[], tags:["mm3","onshape","derek van allen","8 lessons"] },
  "qq_nXVRP9G8": { project:"Marble Machine 3", videoType:"live-stream", instruments:[], tags:["mm3","team wide","design","live"] },
  "lO8Yy0DAfcY": { project:"Marble Machine 3", videoType:"live-stream", instruments:[], tags:["mm3","design requirements","part 3","live"] },
  "GxWIkDDFmQk": { project:"Marble Machine 3", videoType:"live-stream", instruments:[], tags:["mm3","design requirements","part 4","live"] },
  "A0L2bNTBqJU": { project:"Marble Machine 3", videoType:"live-stream", instruments:[], tags:["mm3","transport requirements","constraints","live"] },
  "Xito2etLzfo": { project:"Marble Machine 3", videoType:"build-log", instruments:[], tags:["mm3","monster i learned to love","weekly recap"] },
  "kdtBtiAVMh8": { project:"Marble Machine 3", videoType:"live-stream", instruments:[], tags:["mm3","improving design requirements","live"] },
  "fUDNlsLB4pk": { project:"Marble Machine 3", videoType:"build-log", instruments:[], tags:["mm3","automatic marble sorting","size sorting","weekly recap"] },
  "9MDnHoMi-H8": { project:"Marble Machine 3", videoType:"live-stream", instruments:["vibraphone"], tags:["mm3","vibraphone experiments","live"] },
  "Epr0Ed0bwig": { project:"Marble Machine 3", videoType:"live-stream", instruments:["vibraphone"], tags:["mm3","vibraphone experiments","part 2","live"] },
  "WHxpSkJi6iQ": { project:"Marble Machine 3", videoType:"live-stream", instruments:[], tags:["mm3","first CNC cuts","new machine","live"] },
  "ePS-aoSTzgs": { project:"Marble Machine 3", videoType:"live-stream", instruments:["vibraphone"], tags:["mm3","vibraphone bar holders","how to hold","live"] },
  "UI2b8VDql6g": { project:"Marble Machine 3", videoType:"live-stream", instruments:["vibraphone"], tags:["mm3","vibraphone bar holders","how to hold","live","part 2"] },
  "z6xprYueYec": { project:"Marble Machine 3", videoType:"live-stream", instruments:[], tags:["mm3","design requirements","jasper brookman","live"] },
  "a57vCmURZKA": { project:"Marble Machine 3", videoType:"live-stream", instruments:["vibraphone"], tags:["mm3","3D printed silicone","vibraphone bar holder","test","live"] },
  "-iu6L037yi8": { project:"Marble Machine 3", videoType:"live-stream", instruments:[], tags:["mm3","design requirements organisation","paul drover","live"] },
  "rkDEuUQi9s8": { project:"Marble Machine 3", videoType:"live-stream", instruments:["vibraphone"], tags:["mm3","vibraphone holders","part 3","live"] },
  "lXrJi2X6JSo": { project:"Marble Machine 3", videoType:"live-stream", instruments:["vibraphone"], tags:["mm3","vibraphone holders","part 4","live"] },
  "b01MUffzMQ8": { project:"Marble Machine 3", videoType:"live-stream", instruments:["vibraphone"], tags:["mm3","vibraphone holders","part 3","vertical stream"] },
  "jOYu4zZLELk": { project:"Marble Machine 3", videoType:"live-stream", instruments:["vibraphone"], tags:["mm3","vibraphone holders","part 4","vertical stream"] },
  "t8TSO-7OtK8": { project:"Marble Machine 3", videoType:"educational", instruments:[], tags:["mm3","7 engineering lessons","weekly recap"] },
  "9Kug45MSdhU": { project:"Marble Machine 3", videoType:"live-stream", instruments:["vibraphone","resonator"], tags:["mm3","vibraphone resonator","experiments","theory","live"] },
  "UQBMl0lNWuo": { project:"Marble Machine 3", videoType:"live-stream", instruments:["vibraphone","resonator"], tags:["mm3","vibraphone resonator","prototyping","live"] },
  "-NfmrRx-2b0": { project:"Marble Machine 3", videoType:"live-stream", instruments:["vibraphone"], tags:["mm3","vibraphone 1 channel prototype","live"] },
  "pJJ4GRCK_gI": { project:"Marble Machine 3", videoType:"live-stream", instruments:["vibraphone"], tags:["mm3","vibraphone 1 channel prototype","part 2","live"] },
  "ZKNvUG6nuqc": { project:"Marble Machine 3", videoType:"live-stream", instruments:[], tags:["mm3","design requirements","paul drover","writing","live"] },
  "lWTjeRmOGyA": { project:"Marble Machine 3", videoType:"live-stream", instruments:["vibraphone"], tags:["mm3","vibraphone pivot arm","experiments","live"] },
  "_wslKCTOLQQ": { project:"Marble Machine 3", videoType:"live-stream", instruments:["vibraphone","vibrato","lego"], tags:["mm3","lego vibrato","experiments","live"] },
  "fqkVZue6eaM": { project:"Marble Machine 3", videoType:"live-stream", instruments:["vibraphone","vibrato"], tags:["mm3","vibraphone pivot arm","experiments","vertical stream"] },
  "-1R4UvvlclM": { project:"Marble Machine 3", videoType:"live-stream", instruments:["vibraphone","vibrato","lego"], tags:["mm3","lego vibrato","experiments","vertical stream"] },
  "aF7a14bdfUA": { project:"Marble Machine 3", videoType:"prototype-test", instruments:["vibraphone"], tags:["mm3","moving vibraphone bars","sound test"] },
};

// Merge with raw data
const categorized = raw.map(video => {
  const cat = CAT[video.id] || {
    project: "Other",
    videoType: "channel-update",
    instruments: [],
    tags: [],
  };
  return {
    id: video.id,
    title: video.title,
    description: video.description,
    publishedAt: video.publishedAt,
    thumbnail: video.thumbnail,
    duration: video.duration,
    viewCount: video.viewCount,
    youtubeUrl: video.youtubeUrl,
    project: cat.project,
    videoType: cat.videoType,
    instruments: cat.instruments,
    tags: [...(video.tags || []), ...(cat.tags || [])],
  };
});

const dataDir = new URL('../src/data/', import.meta.url).pathname;
mkdirSync(dataDir, { recursive: true });

writeFileSync(join(dataDir, 'videos.json'), JSON.stringify(categorized, null, 2));

// Lean search index (no description/thumbnail/duration — just what Fuse.js needs)
const index = categorized.map(v => ({
  id: v.id,
  title: v.title,
  project: v.project,
  videoType: v.videoType,
  instruments: v.instruments,
  tags: v.tags,
}));
writeFileSync(join(dataDir, 'videoIndex.json'), JSON.stringify(index));

// Summary
const byProject = {};
const byType = {};
categorized.forEach(v => {
  byProject[v.project] = (byProject[v.project] || 0) + 1;
  byType[v.videoType] = (byType[v.videoType] || 0) + 1;
});

console.log(`\nCategorized ${categorized.length} videos → src/data/videos.json\n`);
console.log('By project:');
Object.entries(byProject).sort((a,b)=>b[1]-a[1]).forEach(([k,v])=>console.log(`  ${v.toString().padStart(3)}  ${k}`));
console.log('\nBy type:');
Object.entries(byType).sort((a,b)=>b[1]-a[1]).forEach(([k,v])=>console.log(`  ${v.toString().padStart(3)}  ${k}`));

const uncategorized = categorized.filter(v => !CAT[v.id]);
if (uncategorized.length) {
  console.log(`\n⚠  ${uncategorized.length} videos fell back to defaults (check CAT table):`);
  uncategorized.forEach(v => console.log(`  ${v.id}  ${v.title}`));
}
